services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=genai_bench
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - cybercq-network

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cybercq-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - cybercq-network

networks:
  cybercq-network:
    driver: bridge

volumes:
  mongo_data:
